@startuml

title __EXCELOPERATIONS's Class Diagram__\n

  namespace ExcelOperations {
    class ExcelOperations.DataProvider {
        ~ ageOfTheStudents : List<Integer>
        ~ headerNames : List<String>
        ~ nameOfTheStudents : List<String>
        ~ numberOfColumns : int
        ~ numberOfRows : int
        ~ totalMarksOfTheStudents : List<Integer>
        + getAgeOfTheStudents()
        + getHeaderNames()
        + getNameOfTheStudents()
        + getNumberOfColumns()
        + getNumberOfRows()
        + getTotalMarksOfTheStudents()
        + setAgeOfTheStudents()
        + setHeaderNames()
        + setNameOfTheStudents()
        + setNumberOfColumns()
        + setNumberOfRows()
        + setTotalMarksOfTheStudents()
    }
  }
  

  namespace ExcelOperations {
    interface ExcelOperations.ExcelOperations {
        {abstract} + checkIfTheGivenHeaderIsPresentOrNot()
        {abstract} + checkTheGivenDataInTheGivenColumn()
        {abstract} + checkTheGivenDataInTheGivenRow()
        {abstract} + getTheNumberOfColumnsInTheFile()
        {abstract} + getTheNumberOfRowsInTheFile()
        {abstract} + getTheValuesFromTheGivenColumnNumber()
        {abstract} + getTheValuesFromTheGivenRowNumber()
        {abstract} + readTheExcelFile()
    }
  }
  

  namespace ExcelOperations {
    class ExcelOperations.Implementor {
        ~ excelFilePath : String
        ~ pathSeparator : String
        ~ scannerObject : Scanner
        ~ userDirectory : String
        + checkIfTheGivenHeaderIsPresentOrNot()
        + checkTheGivenDataInTheGivenColumn()
        + checkTheGivenDataInTheGivenRow()
        + getTheNumberOfColumnsInTheFile()
        + getTheNumberOfRowsInTheFile()
        + getTheValuesFromTheGivenColumnNumber()
        + getTheValuesFromTheGivenRowNumber()
        + readTheExcelFile()
    }
  }
  

  namespace ExcelOperations {
    class ExcelOperations.Runner {
        {static} + main()
    }
  }
  

  ExcelOperations.Implementor .up.|> ExcelOperations.ExcelOperations
  ExcelOperations.Implementor -up-|> ExcelOperations.DataProvider


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
